services:
  waf:
    build: .
    platform: linux/amd64
    ports:
      - "80:3030"      # WAF HTTP
      - "443:3443"     # WAF HTTPS
      - "8888:8888"    # Admin Panel
    env_file:
      - .env
    volumes:
      - ./config/waf.yml:/app/config/waf.yml
      - ./rules:/app/rules:ro
      - waf-certs:/app/config/certs
      - ./logs:/app/logs
      - ./config/ip_whitelist.txt:/app/config/ip_whitelist.txt:ro
      - ./config/ip_blacklist.txt:/app/config/ip_blacklist.txt:ro
      - admin-data:/app/admin/data
      # - ./config/Maxmind/GeoLite2-Country.mmdb:/app/config/Maxmind/GeoLite2-Country.mmdb:ro
    networks:
      - waf-network

  upstream:
    image: ealen/echo-server:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    profiles:
      - upstream
    networks:
      - waf-network

networks:
  waf-network:
    driver: bridge

volumes:
  waf-certs:
  admin-data:
