version: "3.8"

services:
  waf:
    build: .
    platform: linux/amd64
    ports:
      - "80:3030"
      - "443:3443"
    env_file:
      - .env
    volumes:
      - ./config/waf.yml:/app/config/waf.yml:ro
      - ./rules:/app/rules:ro
      - ./config/certs:/app/config/certs
      - ./logs:/app/logs
      - ./config/ip_whitelist.txt:/app/config/ip_whitelist.txt:ro
      - ./config/ip_blacklist.txt:/app/config/ip_blacklist.txt:ro
      # - ./config/Maxmind/GeoLite2-Country.mmdb:/app/config/Maxmind/GeoLite2-Country.mmdb:ro
    depends_on:
      - upstream
    networks:
      - waf-network

  upstream:
    image: ealen/echo-server:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    profiles:
      - upstream
    networks:
      - waf-network

networks:
  waf-network:
    driver: bridge
